version: '{build}'

environment:
  matrix:
  # Comilers matrix
  - env_cmake_generator: "Visual Studio 15 2017"
    env_cmake_configuration: Debug
  - env_cmake_generator: "Visual Studio 15 2017"
    env_cmake_configuration: Release
  - env_cmake_generator: "Visual Studio 15 2017 Win64"
    env_cmake_configuration: Debug
  - env_cmake_generator: "Visual Studio 15 2017 Win64"
    env_cmake_configuration: Release

build_script:
  - mkdir build_cmake
  - pushd build_cmake
  - cmake -G %env_cmake_generator% .. -DCMAKE_BUILD_TYPE=%env_cmake_configuration% -DLIBMOVIE_EXAMPLES_BUILD:BOOL=TRUE -DLIBMOVIE_TEST:BOOL=TRUE -DLIBMOVIE_COVERAGE:BOOL=FALSE
  - cmake --build .
  - ctest --output-on-failure
  - popd
